site_name: Obercom - Portal de Suministros y Logística
site_description: Documentación oficial estandarizada de Obercom

theme:
  name: material
  language: es
  font:
    text: Raleway
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Modo claro
  features:
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - tables
  - md_in_html

nav:
  - 🏠︎ Inicio: index.md
  - 📦 Procedimientos:
      - 📦 PR-ALM-001 Recepción de Insumos: suministros-logistica/PR-ALM-001.md
      - 💰 PR-COM-001 Compras: suministros-logistica/PR-COM-001.md
      - 🔁 PR-REC-001 Recupero de Equipos: suministros-logistica/PR-REC-001.md
      - 👷 PR-PEDT-001 Pedidos Técnicos: suministros-logistica/PR-PEDT-001.md
      - 🏢 PR-PEDS-001 Pedidos Sucursales: suministros-logistica/PR-PEDS-001.md
      - En Desarrollo:
          - PR-HER-001 Reposición de Herramientas: suministros-logistica/PR-HER-001.md
          - PR-AUDS-001 Auditoría de Móviles: suministros-logistica/PR-AUDS-001.md
          - PR-SCR-001 Disposición Final: suministros-logistica/PR-SCR-001.md
          - PR-ENVS-001 Envio entre sucursales: suministros-logistica/PR-ENVS-001.md
  - 🔍 Diagnósticos Técnicos:
      - 🧪 DG-EQU-001 Diagnóstico de equipos devueltos: diagnosticos/DG-EQU-001.md
  - 📄 Plantillas Base:
      - 📄 Procedimientos: plantilla-base.md
      - 🧪 Diagnósticos: plantilla-diagnostico.md
